import {
  ShoppingCart,
  Utensils,
  Bus,
  Fuel,
  Receipt,
  Repeat,
  Home,
  HeartPulse,
  Shirt,
  PartyPopper,
  ShoppingBag,
  GraduationCap,
  Plane,
  CircleEllipsis,
  Wallet,
  TrendingUp,
  TrendingDown,
  LineChart,
  Undo2,
  CirclePlus,
  Tag,
  Coffee,
  Car,
  Gift,
  Baby,
  Dog,
  Dumbbell,
  Smartphone,
  Wifi,
  Droplet,
  Zap,
  Book,
  Music,
  Film,
  Gamepad2,
  Briefcase,
  PiggyBank,
  Banknote,
  CreditCard,
  HandCoins,
  Building2,
  Stethoscope,
  Scissors,
  Pizza,
  Beer,
  type LucideIcon,
} from "lucide-react";

// Kategori ikonları için seçilmiş set (paket boyutunu küçük tutar).
export const ICON_REGISTRY: Record<string, LucideIcon> = {
  "shopping-cart": ShoppingCart,
  utensils: Utensils,
  bus: Bus,
  fuel: Fuel,
  receipt: Receipt,
  repeat: Repeat,
  home: Home,
  "heart-pulse": HeartPulse,
  shirt: Shirt,
  "party-popper": PartyPopper,
  "shopping-bag": ShoppingBag,
  "graduation-cap": GraduationCap,
  plane: Plane,
  "circle-ellipsis": CircleEllipsis,
  wallet: Wallet,
  "trending-up": TrendingUp,
  "trending-down": TrendingDown,
  "line-chart": LineChart,
  "undo-2": Undo2,
  "circle-plus": CirclePlus,
  tag: Tag,
  coffee: Coffee,
  car: Car,
  gift: Gift,
  baby: Baby,
  dog: Dog,
  dumbbell: Dumbbell,
  smartphone: Smartphone,
  wifi: Wifi,
  droplet: Droplet,
  zap: Zap,
  book: Book,
  music: Music,
  film: Film,
  "gamepad-2": Gamepad2,
  briefcase: Briefcase,
  "piggy-bank": PiggyBank,
  banknote: Banknote,
  "credit-card": CreditCard,
  "hand-coins": HandCoins,
  "building-2": Building2,
  stethoscope: Stethoscope,
  scissors: Scissors,
  pizza: Pizza,
  beer: Beer,
};

export const ICON_NAMES = Object.keys(ICON_REGISTRY);

export function CategoryIcon({
  name,
  size = 18,
  className,
}: {
  name: string;
  size?: number;
  className?: string;
}) {
  const Cmp = ICON_REGISTRY[name] ?? Tag;
  return <Cmp size={size} className={className} aria-hidden />;
}
